# Generated by Django 4.1.1 on 2022-09-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnakeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snakeLocation', models.CharField(max_length=900)),
                ('itemLocation', models.CharField(max_length=900)),
            ],
        ),
    ]
