# Generated by Django 4.1.1 on 2022-09-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakebrain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snakestate',
            name='itemLocation',
        ),
        migrations.RemoveField(
            model_name='snakestate',
            name='snakeLocation',
        ),
        migrations.AddField(
            model_name='snakestate',
            name='apples',
            field=models.CharField(default='null', max_length=4000),
        ),
        migrations.AddField(
            model_name='snakestate',
            name='scissors',
            field=models.CharField(default='null', max_length=4000),
        ),
        migrations.AddField(
            model_name='snakestate',
            name='snakeBody',
            field=models.CharField(default='null', max_length=4000),
        ),
        migrations.AddField(
            model_name='snakestate',
            name='snakeHead',
            field=models.CharField(default='null', max_length=4),
        ),
    ]
