# Generated by Django 4.1.1 on 2022-09-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakebrain', '0002_remove_snakestate_itemlocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snakestate',
            name='apples',
        ),
        migrations.RemoveField(
            model_name='snakestate',
            name='scissors',
        ),
        migrations.RemoveField(
            model_name='snakestate',
            name='snakeBody',
        ),
        migrations.RemoveField(
            model_name='snakestate',
            name='snakeHead',
        ),
        migrations.AddField(
            model_name='snakestate',
            name='StateJSON',
            field=models.JSONField(null=True),
        ),
    ]
