# Generated by Django 4.1.1 on 2022-09-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakebrain', '0003_remove_snakestate_apples_remove_snakestate_scissors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snakestate',
            name='StateJSON',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
