# Generated by Django 4.1.1 on 2022-09-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakebrain', '0004_alter_snakestate_statejson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snakestate',
            old_name='StateJSON',
            new_name='statejson',
        ),
        migrations.AddField(
            model_name='snakestate',
            name='gameid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snakestate',
            name='orderid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
