# Generated by Django 4.1.1 on 2022-09-21 11:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakebrain', '0006_remove_snakestate_statejson_snakestate_apples_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snakestate',
            name='apples',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='snakestate',
            name='gameid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snakestate',
            name='orderid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snakestate',
            name='scissors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='snakestate',
            name='snakebody',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='snakestate',
            name='snakehead',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
