# Generated by Django 4.1.1 on 2022-09-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snakebrain', '0008_snakestate_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snakestate',
            old_name='gameid',
            new_name='game_id',
        ),
        migrations.RenameField(
            model_name='snakestate',
            old_name='orderid',
            new_name='order_id',
        ),
    ]
