# Generated by Django 4.1.1 on 2022-10-03 14:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakebrain', '0009_rename_gameid_snakestate_game_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snakestate',
            name='walls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
