# Generated by Django 4.1.1 on 2022-10-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakebrain', '0010_snakestate_walls'),
    ]

    operations = [
        migrations.AddField(
            model_name='snakestate',
            name='done',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snakestate',
            name='reward',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
