# Generated by Django 4.1.1 on 2022-10-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakebrain', '0011_snakestate_done_snakestate_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snakestate',
            name='reward',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
